import {
  IsNotEmpty,
  IsString,
  IsEmail,
  IsEnum,
  IsOptional,
  IsDateString,
  IsPhoneNumber,
} from 'class-validator';
import { Gender } from '../users.entity';
import { Transform } from 'class-transformer';

export class CreateUserDto {
  @IsNotEmpty()
  @IsString()
  firebaseId: string;

  @IsNotEmpty()
  @IsString()
  firstName: string;

  @IsNotEmpty()
  @IsString()
  lastName: string;

  @IsNotEmpty()
  @IsPhoneNumber('US') // Malawi phone number validation
  phoneNumber: string;

  @IsNotEmpty()
  @IsEmail()
  email: string;

  @IsNotEmpty()
  @IsEnum(Gender)
  gender: Gender;

  @IsOptional()
  @Transform(({ value }) => {
    if (typeof value === 'string') {
      // Handle MM/DD/YYYY format
      const date = new Date(value);
      if (!isNaN(date.getTime())) {
        return date.toISOString();
      }
    }
    return typeof value === 'string' ? value : undefined;
  })
  @IsDateString()
  dateOfBirth?: Date;

  // Note: id, createdAt, updatedAt are excluded
  // These are auto-generated by the database
}
