import {
  IsNotEmpty,
  IsString,
  IsEmail,
  IsEnum,
  IsOptional,
  IsDateString,
  IsPhoneNumber,
} from 'class-validator';
import { Gender } from '../users.entity';

export class CreateUserDto {
  @IsNotEmpty()
  @IsString()
  firebaseId: string;

  @IsNotEmpty()
  @IsString()
  firstName: string;

  @IsNotEmpty()
  @IsString()
  lastName: string;

  @IsNotEmpty()
  @IsPhoneNumber('MW') // Malawi phone number validation
  phoneNumber: string;

  @IsNotEmpty()
  @IsEmail()
  email: string;

  @IsNotEmpty()
  @IsEnum(Gender)
  gender: Gender;

  @IsOptional()
  @IsDateString()
  dateOfBirth?: Date;

  // Note: id, createdAt, updatedAt are excluded
  // These are auto-generated by the database
}
